name: Build & Publish Release APK

on:
  push:
    branches:
      - github/release #Only do this for special branches if you need the artifact built and stored on github. It messes up the versioning on Play Store

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install NDK
        run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT}
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build --warning-mode all
      - name: Build Debug APK
        run: ./gradlew assembleRelease
      - name: Release APK Publisher
        uses: nightcrawler-/action-release-apk@1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          APP_FOLDER: app
          RELEASE_TITLE: ${{ github.run_number }}